name: Build and Push Django Container to GHCR

on:
  push:
    branches: [main]
    tags: ['v*']  # triggers on tags like v1.0.0, v2.3.1, etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract_tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/ccarver031783/petstagram-backend:latest \
                       -t ghcr.io/ccarver031783/petstagram-backend:${{ env.VERSION }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/ccarver031783/petstagram-backend:latest
          docker push ghcr.io/ccarver031783/petstagram-backend:${{ env.VERSION }}
