apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: signuprequests.petstagram.io
spec:
  group: petstagram.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
  scope: Namespaced
  names:
    plural: signuprequests
    singular: signuprequest
    kind: SignupRequest
    shortNames:
      - su
