apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userprofileservices.petbook.dev
spec:
  group: petbook.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
            status:
              type: object
              properties:
                message:
                  type: string
  scope: Namespaced
  names:
    plural: userprofileservices
    singular: userprofileservice
    kind: UserProfileService