apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      port: 80         # External port exposed to users
      targetPort: 8000 # Internal port your Django app listens on
  type: NodePort       # Use LoadBalancer if you're on a cloud provider
